version: '3'
services:
  scheduler-node-a:
    image: vaslabs/workscheduler:0.1.0-SNAPSHOT
    ports:
    - "8080:8080"
    - "8558:8558"
    volumes:
      - ./scheduler-node-a/config:/opt/docker/conf:z
  scheduler-node-b:
    image: vaslabs/workscheduler:0.1.0-SNAPSHOT
    ports:
      - "8081:8080"
      - "8559:8558"
    volumes:
      - ./scheduler-node-a/config:/opt/docker/conf:z
