image: hseeberger/scala-sbt:8u222_1.3.4_2.13.1

stages:
  - build
  - publish
  - deploy


build:
  stage: build
  script:
    - sbt test

publish:
  stage: build
  before_script:
    - curl -sSL https://get.docker.com/ | sh
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  services:
    - dind
  script:
    - sbt docker:publish

deploy:
  stage: deploy
  when: manual
  script:
    - echo Not setup



